/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.Optional;

public class App {
    public static void main(String[] args) {
        // p.s. Добавил отрицательные значения, несмотря на условие [0, ∞),
        // т.к. суть задания - найти АБСОЛЮТНОЕ значение
        Integer[] numbers = { -1, -23, 1, 4, 6, 7, 15 };
        System.out.println("Исходный массив: " + Arrays.toString(numbers));

        var arrayComparator = new ArraysComparator<>(numbers);
        Optional<Integer> result = arrayComparator.findAbsMax();
        result.ifPresentOrElse(
                v -> System.out.println("Максимальное значение по модулю: " + Math.abs(v)),
                        () -> System.out.println("Произошла ошибка при обработке массива"));

        //Исходный массив: [-1, -23, 1, 4, 6, 7, 15]
        //Максимальное значение по модулю: 23
    }
}
